---
driver:
  name: vagrant
use_vagrant_berkshelf_plugin: true
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      box: ubuntu-12-x64
      box_url: https://s3.amazonaws.com/vagrant-bx/ubuntu-12-x64.box
  - name: ubuntu-10.04
    driver:
      box: ubuntu-10-x64
      box_url: https://s3.amazonaws.com/vagrant-bx/ubuntu-10-x64.box
  - name: centos-6.4
    driver:
      box: centos_6_x64
      box_url: https://s3.amazonaws.com/vagrant-bx/centos-6-x64.box
  - name: centos-5.6
    driver:
      box: centos-5-x64
      box_url: https://s3.amazonaws.com/vagrant-bx/centos-5-x64.box

suites:
  - name: default
    run_list:
      - recipe[solr_test::default]
    attributes: {
                  solr: {
                    port: "8080",
                    loglevel: "FINEST"
                  },
                }
  - name: default-zoo
    run_list:
      - recipe[solr_test::default_zoo]
    attributes: {
                  solr: {
                    port: "8080",
                    loglevel: "FINEST",
                    zookeeper: {
                      hosts: ["127.0.0.1"],
                      port: "2181"}
                  },
                }
  - name: create-collection 
    run_list:
      - recipe[solr_test::create_collection]
    attributes: {
                  solr: {
                    port: "8080",
                    loglevel: "FINEST",
                    collection: ["testcoll1", "testcoll2"]
                  },
                }
  - name: create-collection-zoo 
    run_list:
      - recipe[zookeeper-component]
      - recipe[solr_test::create_collection_zoo]
    attributes: {
                  solr: {
                    port: "8080",
                    loglevel: "FINEST",
                    collection: ["testcoll1", "testcoll2"],
                    zookeeper: {
                      hosts: ["127.0.0.1"],
                      port: "2181"}
                  },
                  exhibitor: {
                    opts: {
                      port: "8090"
                    }
                  }
                }

